
import { Candidate, Job } from '../types';

export const MOCK_CANDIDATES: Candidate[] = [
  // --- EXISTING CANDIDATES (c1-c5) ---
  {
    id: 'c1',
    name: 'Ana Silva',
    role: 'SDR',
    seniority: 'Pleno',
    avatarUrl: 'https://ui-avatars.com/api/?name=Ana+Silva&background=f97316&color=fff&size=256',
    bio: 'Especialista em prospecção outbound com foco em SaaS.',
    location: 'São Paulo, SP',
    skills: ['Cold Calling', 'CRM HubSpot', 'LinkedIn Sales Nav', 'Copywriting'],
    salaryExpectation: 4500,
    phone: '5511999991111',
    resumeUrl: 'ana_silva_cv.pdf',
    archetype: 'Hunter Resiliente',
    personalitySummary: 'Perfil altamente orientado a resultados, com baixíssima aversão à rejeição.',
    likelyBehavior: 'Tende a ser direta e objetiva. Foca em volume e conversão.',
    areaOfPotency: 'Vendas Outbound de alto volume.',
    topSubTraits: ['Autodisciplina', 'Energia', 'Regulação'],
    sincerityScore: 92,
    bigFive: { openness: 65, conscientiousness: 92, extraversion: 78, agreeableness: 45, stability: 88 },
    subTraits: { 
        ambicao: 90, autodisciplina: 95, planejado: 85, perfeccionismo: 70, 
        praticidade: 92, sociabilidade: 60, desinibicao: 80, influencia: 75, 
        energia: 88, autoconfianca: 85, julgamento: 70, competicao: 95, 
        imaginacao: 50, abertura: 60, regulacao: 88, temperamento: 85,
        impulsividade: 20, vulnerabilidade: 15, sensibilidade: 40, confronto: 85 
    }
  },
  {
    id: 'c2',
    name: 'Carlos Mendes',
    role: 'Account Executive',
    seniority: 'Sênior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Carlos+Mendes&background=0f172a&color=fff&size=256',
    bio: 'Closer experiente em vendas complexas B2B.',
    location: 'Remoto',
    skills: ['Negociação', 'SPIN Selling', 'Salesforce', 'Fechamento'],
    salaryExpectation: 12000,
    phone: '5521988882222',
    archetype: 'Closer Estratégico',
    personalitySummary: 'Estrategista nato. Utiliza análise e influência para fechar.',
    likelyBehavior: 'Assume o controle da sala. Investiga profundamente.',
    areaOfPotency: 'Vendas Enterprise e Negociações Complexas.',
    topSubTraits: ['Influência', 'Julgamento', 'Temperamento'],
    sincerityScore: 85,
    bigFive: { openness: 70, conscientiousness: 85, extraversion: 82, agreeableness: 30, stability: 95 },
    subTraits: { 
        ambicao: 85, autodisciplina: 80, planejado: 90, perfeccionismo: 60, 
        praticidade: 85, sociabilidade: 70, desinibicao: 75, influencia: 95, 
        energia: 80, autoconfianca: 92, julgamento: 95, competicao: 80, 
        imaginacao: 65, abertura: 70, regulacao: 95, temperamento: 90,
        impulsividade: 30, vulnerabilidade: 10, sensibilidade: 30, confronto: 90
    }
  },
  {
    id: 'c3',
    name: 'Beatriz Costa',
    role: 'CS',
    seniority: 'Júnior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Beatriz+Costa&background=7c3aed&color=fff&size=256',
    bio: 'Apaixonada por sucesso do cliente e retenção.',
    location: 'Rio de Janeiro, RJ',
    skills: ['Onboarding', 'Zendesk', 'Churn Reduction', 'Upsell'],
    salaryExpectation: 3500,
    phone: '5521977773333',
    archetype: 'Diplomata Empática',
    personalitySummary: 'Extremamente orientada a pessoas e resolução de conflitos.',
    likelyBehavior: 'Ouve mais do que fala. Busca o "ganha-ganha".',
    areaOfPotency: 'Customer Success e Onboarding.',
    topSubTraits: ['Sociabilidade', 'Imaginação', 'Abertura'],
    sincerityScore: 98,
    bigFive: { openness: 60, conscientiousness: 75, extraversion: 65, agreeableness: 95, stability: 70 },
    subTraits: { 
        ambicao: 50, autodisciplina: 70, planejado: 75, perfeccionismo: 80, 
        praticidade: 60, sociabilidade: 95, desinibicao: 60, influencia: 70, 
        energia: 75, autoconfianca: 65, julgamento: 50, competicao: 40, 
        imaginacao: 80, abertura: 75, regulacao: 70, temperamento: 80,
        impulsividade: 40, vulnerabilidade: 40, sensibilidade: 95, confronto: 20
    }
  },
  {
    id: 'c4',
    name: 'João Pereira',
    role: 'SDR',
    seniority: 'Júnior',
    avatarUrl: 'https://ui-avatars.com/api/?name=João+Pereira&background=334155&color=fff&size=256',
    bio: 'Iniciando carreira em vendas.',
    location: 'Belo Horizonte, MG',
    skills: ['Cold Calling', 'Pesquisa de Mercado', 'Google Sheets'],
    salaryExpectation: 2500,
    phone: '5531966664444',
    archetype: 'Aprendiz Ágil',
    personalitySummary: 'Curioso e rápido para aprender, mas falta disciplina.',
    likelyBehavior: 'Entusiasmado e criativo, porém disperso.',
    areaOfPotency: 'Pré-vendas em Startups early-stage.',
    topSubTraits: ['Curiosidade', 'Energia', 'Abertura'],
    sincerityScore: 45, // Low sincerity
    bigFive: { openness: 90, conscientiousness: 60, extraversion: 70, agreeableness: 80, stability: 50 },
    subTraits: { 
        ambicao: 65, autodisciplina: 50, planejado: 55, perfeccionismo: 40, 
        praticidade: 60, sociabilidade: 85, desinibicao: 70, influencia: 65, 
        energia: 90, autoconfianca: 60, julgamento: 60, competicao: 55, 
        imaginacao: 95, abertura: 95, regulacao: 50, temperamento: 60,
        impulsividade: 80, vulnerabilidade: 60, sensibilidade: 70, confronto: 40
    }
  },
  {
    id: 'c5',
    name: 'Fernanda Lima',
    role: 'Account Executive',
    seniority: 'Pleno',
    avatarUrl: 'https://ui-avatars.com/api/?name=Fernanda+Lima&background=db2777&color=fff&size=256',
    bio: 'Foco em expansão de contas e vendas consultivas.',
    location: 'São Paulo, SP',
    skills: ['Negociação', 'CRM HubSpot', 'Relacionamento', 'Forecast'],
    salaryExpectation: 8000,
    phone: '5511955555555',
    archetype: 'Consultora de Relacionamento',
    personalitySummary: 'Equilíbrio entre relacionamento e meta.',
    likelyBehavior: 'Networking natural. Mantém CRM organizado.',
    areaOfPotency: 'Farmer e Vendas de Serviços.',
    topSubTraits: ['Sociabilidade', 'Ambição', 'Organização'],
    sincerityScore: 78,
    bigFive: { openness: 75, conscientiousness: 80, extraversion: 88, agreeableness: 75, stability: 75 },
    subTraits: { 
        ambicao: 80, autodisciplina: 80, planejado: 85, perfeccionismo: 75, 
        praticidade: 80, sociabilidade: 95, desinibicao: 90, influencia: 85, 
        energia: 90, autoconfianca: 85, julgamento: 75, competicao: 70, 
        imaginacao: 75, abertura: 80, regulacao: 75, temperamento: 80,
        impulsividade: 40, vulnerabilidade: 30, sensibilidade: 80, confronto: 60
    }
  },

  // --- NEW CANDIDATES (c6-c35) ---
  
  // High Profile Executives
  {
    id: 'c6',
    name: 'Roberto Almeida',
    role: 'Head Comercial',
    seniority: 'Sênior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Roberto+Almeida&background=1e293b&color=fff',
    bio: 'Liderança de times de alta performance (50+ pessoas).',
    location: 'São Paulo, SP',
    skills: ['Liderança', 'Gestão de Pipeline', 'Forecast', 'Coaching'],
    salaryExpectation: 25000,
    phone: '5511911112222',
    archetype: 'Líder Estrategista',
    personalitySummary: 'Alta dominância e visão sistêmica. Focado em números mas com habilidade política.',
    likelyBehavior: 'Exigente com métricas, inspirador em reuniões.',
    areaOfPotency: 'Scale-ups e Reestruturação Comercial.',
    topSubTraits: ['Liderança', 'Ambição', 'Estabilidade'],
    sincerityScore: 88,
    bigFive: { openness: 80, conscientiousness: 95, extraversion: 85, agreeableness: 50, stability: 90 },
    subTraits: { 
        ambicao: 98, autodisciplina: 95, planejado: 90, perfeccionismo: 85, 
        praticidade: 95, sociabilidade: 80, desinibicao: 70, influencia: 95, 
        energia: 90, autoconfianca: 95, julgamento: 90, competicao: 90, 
        imaginacao: 75, abertura: 80, regulacao: 95, temperamento: 90,
        impulsividade: 20, vulnerabilidade: 10, sensibilidade: 40, confronto: 90
    }
  },
  
  // SDRs
  {
    id: 'c7',
    name: 'Júlia Santos',
    role: 'SDR',
    seniority: 'Júnior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Julia+Santos&background=f472b6&color=fff',
    bio: 'Transição de carreira, ex-atleta, muita disciplina.',
    location: 'Curitiba, PR',
    skills: ['Disciplina', 'Treinável', 'Prospecção'],
    salaryExpectation: 2500,
    phone: '5541922223333',
    archetype: 'Hunter Resiliente',
    personalitySummary: 'Perfil "trator". Alta energia e baixa sensibilidade a negativas.',
    likelyBehavior: 'Segue o script à risca. Ótima para volume.',
    areaOfPotency: 'Cold Call e Prospecção Massiva.',
    topSubTraits: ['Disciplina', 'Energia', 'Competição'],
    sincerityScore: 95,
    bigFive: { openness: 40, conscientiousness: 90, extraversion: 60, agreeableness: 40, stability: 85 },
    subTraits: { 
        ambicao: 85, autodisciplina: 95, planejado: 80, perfeccionismo: 60, 
        praticidade: 90, sociabilidade: 50, desinibicao: 60, influencia: 55, 
        energia: 90, autoconfianca: 80, julgamento: 40, competicao: 90, 
        imaginacao: 30, abertura: 40, regulacao: 85, temperamento: 85,
        impulsividade: 20, vulnerabilidade: 20, sensibilidade: 30, confronto: 80
    }
  },
  {
    id: 'c8',
    name: 'Lucas Ferreira',
    role: 'SDR',
    seniority: 'Pleno',
    avatarUrl: 'https://ui-avatars.com/api/?name=Lucas+Ferreira&background=3b82f6&color=fff',
    bio: 'Top Performer no último trimestre. Foco em Enterprise.',
    location: 'Remoto',
    skills: ['LinkedIn Sales Nav', 'Email Marketing', 'Copywriting'],
    salaryExpectation: 4000,
    phone: '5511933334444',
    archetype: 'Hunter Estratégico',
    personalitySummary: 'Inteligente na prospecção. Pesquisa antes de ligar.',
    likelyBehavior: 'Qualidade sobre quantidade. Personaliza abordagens.',
    areaOfPotency: 'Account Based Marketing (ABM).',
    topSubTraits: ['Investigação', 'Planejamento', 'Persuasão'],
    sincerityScore: 82,
    bigFive: { openness: 75, conscientiousness: 85, extraversion: 65, agreeableness: 60, stability: 80 },
    subTraits: { 
        ambicao: 80, autodisciplina: 85, planejado: 90, perfeccionismo: 75, 
        praticidade: 80, sociabilidade: 60, desinibicao: 65, influencia: 75, 
        energia: 75, autoconfianca: 80, julgamento: 85, competicao: 75, 
        imaginacao: 70, abertura: 75, regulacao: 80, temperamento: 80,
        impulsividade: 30, vulnerabilidade: 25, sensibilidade: 50, confronto: 70
    }
  },
  {
    id: 'c9',
    name: 'Gabriel Souza',
    role: 'SDR',
    seniority: 'Júnior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Gabriel+Souza&background=22c55e&color=fff',
    bio: 'Gosto de conversar e vender ideias.',
    location: 'Salvador, BA',
    skills: ['Comunicação', 'Vendas', 'Persuasão'],
    salaryExpectation: 2200,
    phone: '5571944445555',
    archetype: 'Comunicador Nato',
    personalitySummary: 'Extrovertido ao extremo, mas desorganizado. Pode ter problemas com CRM.',
    likelyBehavior: 'Ótimo em quebrar gelo, péssimo em follow-up estruturado.',
    areaOfPotency: 'Vendas de Impacto Rápido.',
    topSubTraits: ['Sociabilidade', 'Desinibição', 'Improviso'],
    sincerityScore: 60, // Sincerity Warning
    bigFive: { openness: 70, conscientiousness: 30, extraversion: 95, agreeableness: 80, stability: 60 },
    subTraits: { 
        ambicao: 60, autodisciplina: 20, planejado: 25, perfeccionismo: 30, 
        praticidade: 50, sociabilidade: 98, desinibicao: 95, influencia: 90, 
        energia: 90, autoconfianca: 85, julgamento: 60, competicao: 50, 
        imaginacao: 75, abertura: 70, regulacao: 50, temperamento: 60,
        impulsividade: 85, vulnerabilidade: 50, sensibilidade: 75, confronto: 50
    }
  },

  // Account Executives / Closers
  {
    id: 'c10',
    name: 'Patricia Lima',
    role: 'Account Executive',
    seniority: 'Sênior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Patricia+Lima&background=a855f7&color=fff',
    bio: 'Venda Consultiva de Software ERP.',
    location: 'São Paulo, SP',
    skills: ['Venda Consultiva', 'BANT', 'Demonstração de Produto'],
    salaryExpectation: 10000,
    phone: '5511955556666',
    archetype: 'Closer Consultiva',
    personalitySummary: 'Metódica e confiável. O cliente confia nela tecnicamente.',
    likelyBehavior: 'Venda baseada em confiança e dados.',
    areaOfPotency: 'Vendas Técnicas e Complexas.',
    topSubTraits: ['Conhecimento', 'Estabilidade', 'Confiança'],
    sincerityScore: 90,
    bigFive: { openness: 60, conscientiousness: 88, extraversion: 60, agreeableness: 70, stability: 92 },
    subTraits: { 
        ambicao: 75, autodisciplina: 90, planejado: 92, perfeccionismo: 85, 
        praticidade: 80, sociabilidade: 55, desinibicao: 50, influencia: 70, 
        energia: 70, autoconfianca: 85, julgamento: 80, competicao: 60, 
        imaginacao: 50, abertura: 60, regulacao: 95, temperamento: 90,
        impulsividade: 15, vulnerabilidade: 10, sensibilidade: 50, confronto: 65
    }
  },
  {
    id: 'c11',
    name: 'Ricardo Gomes',
    role: 'Closer',
    seniority: 'Pleno',
    avatarUrl: 'https://ui-avatars.com/api/?name=Ricardo+Gomes&background=ef4444&color=fff',
    bio: 'Faca na caveira. Fechamento agressivo.',
    location: 'Rio de Janeiro, RJ',
    skills: ['Fechamento', 'Objeções', 'Persuasão'],
    salaryExpectation: 7000,
    phone: '5521966667777',
    archetype: 'Lobo Solitário',
    personalitySummary: 'Alta ambição, baixa amabilidade. Fecha a venda custe o que custar.',
    likelyBehavior: 'Pressiona o cliente. Pode gerar churn se vender errado.',
    areaOfPotency: 'Vendas Transacionais Rápidas.',
    topSubTraits: ['Competição', 'Ambição', 'Influência'],
    sincerityScore: 40, // Liar / Exaggerator
    bigFive: { openness: 50, conscientiousness: 70, extraversion: 85, agreeableness: 20, stability: 80 },
    subTraits: { 
        ambicao: 95, autodisciplina: 70, planejado: 60, perfeccionismo: 50, 
        praticidade: 90, sociabilidade: 70, desinibicao: 85, influencia: 90, 
        energia: 85, autoconfianca: 95, julgamento: 60, competicao: 98, 
        imaginacao: 40, abertura: 50, regulacao: 75, temperamento: 80,
        impulsividade: 50, vulnerabilidade: 20, sensibilidade: 15, confronto: 95
    }
  },
  {
    id: 'c12',
    name: 'Mariana Ximenes',
    role: 'Account Executive',
    seniority: 'Pleno',
    avatarUrl: 'https://ui-avatars.com/api/?name=Mariana+Ximenes&background=f59e0b&color=fff',
    bio: 'Experiência com vendas internacionais.',
    location: 'Florianópolis, SC',
    skills: ['Inglês Fluente', 'Vendas Global', 'Tech'],
    salaryExpectation: 9000,
    phone: '5548977778888',
    archetype: 'Global Seller',
    personalitySummary: 'Alta abertura ao novo, adaptável a culturas diferentes.',
    likelyBehavior: 'Curiosa e adaptável. Boa ouvinte.',
    areaOfPotency: 'Expansão Internacional.',
    topSubTraits: ['Abertura', 'Curiosidade', 'Adaptação'],
    sincerityScore: 88,
    bigFive: { openness: 95, conscientiousness: 75, extraversion: 75, agreeableness: 80, stability: 80 },
    subTraits: { 
        ambicao: 75, autodisciplina: 75, planejado: 70, perfeccionismo: 60, 
        praticidade: 70, sociabilidade: 80, desinibicao: 75, influencia: 75, 
        energia: 80, autoconfianca: 80, julgamento: 80, competicao: 65, 
        imaginacao: 90, abertura: 98, regulacao: 80, temperamento: 80,
        impulsividade: 35, vulnerabilidade: 20, sensibilidade: 60, confronto: 60
    }
  },

  // CS / Farmers
  {
    id: 'c13',
    name: 'Eduardo Rocha',
    role: 'CS',
    seniority: 'Sênior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Eduardo+Rocha&background=64748b&color=fff',
    bio: 'Especialista em Key Accounts e Upsell.',
    location: 'Porto Alegre, RS',
    skills: ['Gestão de Contas', 'Relacionamento', 'Upsell'],
    salaryExpectation: 8500,
    phone: '5551988889999',
    archetype: 'Trusted Advisor',
    personalitySummary: 'O cliente vê nele um parceiro de negócios, não um vendedor.',
    likelyBehavior: 'Consultivo, paciente, focado no longo prazo.',
    areaOfPotency: 'Gestão de Grandes Contas (Farmer).',
    topSubTraits: ['Empatia', 'Planejamento', 'Paciência'],
    sincerityScore: 92,
    bigFive: { openness: 60, conscientiousness: 85, extraversion: 60, agreeableness: 90, stability: 90 },
    subTraits: { 
        ambicao: 60, autodisciplina: 90, planejado: 90, perfeccionismo: 75, 
        praticidade: 70, sociabilidade: 75, desinibicao: 50, influencia: 65, 
        energia: 60, autoconfianca: 80, julgamento: 70, competicao: 40, 
        imaginacao: 50, abertura: 60, regulacao: 95, temperamento: 95,
        impulsividade: 15, vulnerabilidade: 10, sensibilidade: 85, confronto: 40
    }
  },
  {
    id: 'c14',
    name: 'Sofia Martins',
    role: 'CS',
    seniority: 'Júnior',
    avatarUrl: 'https://ui-avatars.com/api/?name=Sofia+Martins&background=ec4899&color=fff',
    bio: 'Adoro resolver problemas e ajudar pessoas.',
    location: 'Remoto',
    skills: ['Empatia', 'Resolução de Problemas', 'Comunicação'],
    salaryExpectation: 3000,
    phone: '5511999990000',
    archetype: 'Helper',
    personalitySummary: 'Altíssima amabilidade, mas pode ter dificuldade em dizer não.',
    likelyBehavior: 'Defensora do cliente. Precisa de treino em negociação.',
    areaOfPotency: 'Suporte Avançado e Onboarding.',
    topSubTraits: ['Altruísmo', 'Empatia', 'Cooperação'],
    sincerityScore: 85,
    bigFive: { openness: 55, conscientiousness: 70, extraversion: 70, agreeableness: 98, stability: 60 },
    subTraits: { 
        ambicao: 40, autodisciplina: 65, planejado: 60, perfeccionismo: 50, 
        praticidade: 50, sociabilidade: 85, desinibicao: 60, influencia: 55, 
        energia: 70, autoconfianca: 60, julgamento: 40, competicao: 20, 
        imaginacao: 60, abertura: 55, regulacao: 60, temperamento: 65,
        impulsividade: 30, vulnerabilidade: 50, sensibilidade: 95, confronto: 15
    }
  },

  // Management / Ops
  {
    id: 'c15',
    name: 'Bruno Dias',
    role: 'Sales Ops',
    seniority: 'Pleno',
    avatarUrl: 'https://ui-avatars.com/api/?name=Bruno+Dias&background=06b6d4&color=fff',
    bio: 'Dados, Dashboards e Processos.',
    location: 'Belo Horizonte, MG',
    skills: ['SQL', 'PowerBI', 'Salesforce Admin', 'Excel'],
    salaryExpectation: 6500,
    phone: '5531912341234',
    archetype: 'Analista Lógico',
    personalitySummary: 'Introvertido, analítico e detalhista. Zero perfil de vendas, 100% backoffice.',
    likelyBehavior: 'Focado na tela, não em pessoas. Encontra erros que ninguém vê.',
    areaOfPotency: 'Inteligência Comercial e Processos.',
    topSubTraits: ['Análise', 'Perfeccionismo', 'Lógica'],
    sincerityScore: 96,
    bigFive: { openness: 50, conscientiousness: 98, extraversion: 20, agreeableness: 60, stability: 85 },
    subTraits: { 
        ambicao: 60, autodisciplina: 98, planejado: 98, perfeccionismo: 98, 
        praticidade: 90, sociabilidade: 20, desinibicao: 10, influencia: 30, 
        energia: 50, autoconfianca: 70, julgamento: 95, competicao: 40, 
        imaginacao: 40, abertura: 50, regulacao: 85, temperamento: 85,
        impulsividade: 10, vulnerabilidade: 10, sensibilidade: 30, confronto: 50
    }
  },
  
  // Real names to fill the pool
  ...[
    "Amanda Souza", "Rafael Oliveira", "Camila Santos", "Thiago Lima", "Larissa Costa",
    "Felipe Pereira", "Juliana Rodrigues", "Rodrigo Alves", "Bianca Ferreira", "Gustavo Silva",
    "Letícia Martins", "André Gomes", "Fernanda Barbosa", "Marcelo Ribeiro", "Vitória Melo",
    "Guilherme Cardoso", "Isabela Nogueira", "Matheus Rocha", "Carolina Teixeira", "Diego Miranda"
  ].map((name, i) => ({
    id: `c${i + 16}`,
    name: name,
    role: ['SDR', 'BDR', 'Closer', 'CS', 'Account Executive'][Math.floor(Math.random() * 5)] as any,
    seniority: ['Júnior', 'Pleno', 'Sênior'][Math.floor(Math.random() * 3)] as any,
    avatarUrl: `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=random&color=fff`,
    bio: 'Profissional dedicado em busca de novas oportunidades e desafios na área comercial.',
    location: ['São Paulo, SP', 'Rio de Janeiro, RJ', 'Remoto', 'Curitiba, PR', 'Belo Horizonte, MG'][Math.floor(Math.random() * 5)],
    skills: ['Vendas', 'CRM', 'Comunicação', 'Negociação'],
    salaryExpectation: 3000 + Math.floor(Math.random() * 7000),
    phone: '5511900000000',
    archetype: 'Generalista',
    personalitySummary: 'Perfil equilibrado com potencial de desenvolvimento.',
    likelyBehavior: 'Adaptável e colaborativo.',
    areaOfPotency: 'Vendas Gerais.',
    topSubTraits: ['Esforço', 'Adaptação'],
    sincerityScore: 60 + Math.floor(Math.random() * 40),
    bigFive: { 
        openness: 40 + Math.floor(Math.random() * 40),
        conscientiousness: 40 + Math.floor(Math.random() * 40),
        extraversion: 40 + Math.floor(Math.random() * 40),
        agreeableness: 40 + Math.floor(Math.random() * 40),
        stability: 40 + Math.floor(Math.random() * 40)
    },
    subTraits: { 
        ambicao: 50, autodisciplina: 50, planejado: 50, perfeccionismo: 50, 
        praticidade: 50, sociabilidade: 50, desinibicao: 50, influencia: 50, 
        energia: 50, autoconfianca: 50, julgamento: 50, competicao: 50, 
        imaginacao: 50, abertura: 50, regulacao: 50, temperamento: 50,
        impulsividade: 50, vulnerabilidade: 50, sensibilidade: 50, confronto: 50
    }
  }))
];

export const MOCK_JOBS: Job[] = [
   {
    id: 'j1',
    title: 'SDR Outbound - SaaS',
    company: 'TechGrowth',
    role: 'SDR',
    seniority: 'Pleno',
    location: 'São Paulo (Híbrido)',
    description: 'Buscamos um SDR Hunter obstinado para escalar nossa operação.',
    challenges: ['Estruturar processos de prospecção do zero.', 'Realizar 60+ touchpoints diários.', 'Aumentar taxa de conversão MQL->SQL.'],
    salaryRange: [4000, 5000],
    requiredSkills: ['Cold Calling', 'CRM HubSpot', 'LinkedIn Sales Nav'],
    cultureFit: ['Resiliência', 'Ambição', 'Proatividade'],
    active: true,
    postedAt: '2023-10-25',
    companyDescription: 'Scale-up líder em automação de marketing. Nascemos para ajudar empresas B2B a vender mais através de tecnologia proprietária e inteligência artificial.',
    productSolution: 'Plataforma All-in-One de Automação de Marketing e Vendas, resolvendo a desconexão entre Leads gerados e Vendas fechadas.',
    website: 'https://techgrowth.com.br',
    instagram: 'https://instagram.com/techgrowth',
    compensationDetails: 'CLT Full R$ 4.500 + Comissão de R$ 50 por agendamento qualificado + Bônus trimestral.',
    deadline: '2023-11-15',
    icp: 'Gestores de Marketing e Vendas de empresas B2B com +50 funcionários e faturamento anual > R$ 10M.',
    idealProfile: 'Profissional com perfil "Hunter", alta energia, que não se abala com "nãos". Precisa ter disciplina férrea para cumprir o volume de atividades diárias.',
    techStack: ['HubSpot CRM', 'LinkedIn Sales Navigator', 'Apollo.io', 'Slack', 'Meetime'],
    dailyRoutine: ['09:00 - Reunião Matinal', '09:30 - Prospecção Ativa (Bloco 1)', '12:00 - Almoço', '13:30 - Follow-ups e E-mails', '15:00 - Prospecção Ativa (Bloco 2)', '17:30 - Organização do CRM'],
    tacticalMandate: "Para esta missão na TechGrowth, o cenário é claro: precisamos de alguém capaz de evangelizar e vender Plataforma All-in-One de Automação de Marketing e Vendas diretamente para Gestores de Marketing e Vendas de empresas B2B com +50 funcionários e faturamento anual > R$ 10M, navegando por tomadores de decisão exigentes. O perfil tático é de um 'Hunter' obstinado: alguém que suporte a rejeição, cumpra a cadência de prospecção sem falhas e alimente o pipeline. O principal obstáculo será estruturar processos de prospecção do zero, exigindo resiliência diária. A recompensa está na mesa: pacote de até R$ 5k com CLT Full R$ 4.500 + Comissão de R$ 50 por agendamento qualificado + Bônus trimestral."
  },
  {
    id: 'j2',
    title: 'Closer Enterprise',
    company: 'BigCorp Solutions',
    role: 'Account Executive',
    seniority: 'Sênior',
    location: 'Remoto',
    description: 'Executivo de contas estratégico focado em grandes logos.',
    challenges: ['Penetrar em contas Enterprise.', 'Ciclo de vendas de 6-12 meses.', 'Negociar contratos complexos.'],
    salaryRange: [10000, 15000],
    requiredSkills: ['Negociação', 'Salesforce', 'SPIN Selling', 'Fechamento'],
    cultureFit: ['Liderança', 'Foco em Resultados', 'Autonomia'],
    active: true,
    postedAt: '2023-10-20',
    companyDescription: 'Multinacional referência em ERP, com mais de 30 anos de mercado e presença em 15 países.',
    productSolution: 'ERP Cloud Robust para Indústrias, solucionando a falta de integração entre chão de fábrica e escritório administrativo.',
    website: 'https://bigcorp.com',
    instagram: 'https://instagram.com/bigcorp_careers',
    compensationDetails: 'PJ. Fixo R$ 12k + Variável Trimestral baseada em % do TCV (Total Contract Value). Média de ganhos R$ 25k/mês.',
    deadline: '2023-11-30',
    icp: 'CTOs, CFOs e Diretores Industriais de empresas com faturamento acima de R$ 500M/ano.',
    idealProfile: 'Vendedor consultivo, com postura executiva e paciência estratégica. Capaz de navegar em hierarquias complexas e construir relacionamentos de longo prazo.',
    techStack: ['Salesforce', 'Gong.io', 'DocuSign', 'Zoom', 'Tableau'],
    dailyRoutine: ['09:00 - Revisão de Pipeline', '10:00 - Demos e Reuniões de Descoberta', '14:00 - Negociação de Contratos', '16:00 - Alinhamento com Sales Engineer', '17:00 - Prospecção de Contas Nomeadas'],
    tacticalMandate: "Para esta missão na BigCorp Solutions, o cenário é claro: precisamos de alguém capaz de evangelizar e vender ERP Cloud Robust para Indústrias diretamente para CTOs, CFOs e Diretores Industriais de empresas com faturamento acima de R$ 500M/ano, navegando por tomadores de decisão exigentes. Buscamos um 'Closer' estratégico: alguém que controle a sala, desarme objeções complexas e tenha a paciência para ciclos de venda longos. O principal obstáculo será penetrar em contas enterprise, exigindo resiliência diária. A recompensa está na mesa: pacote de até R$ 15k com PJ. Fixo R$ 12k + Variável Trimestral baseada em % do TCV (Total Contract Value). Média de ganhos R$ 25k/mês."
  },
  {
    id: 'j3',
    title: 'SDR Inbound',
    company: 'StartVendas',
    role: 'SDR',
    seniority: 'Júnior',
    location: 'Remoto',
    description: 'Qualificação inicial de leads gerados por marketing.',
    challenges: ['Reduzir Lead Time para < 5 min.', 'Volume alto de leads.', 'Organização impecável de CRM.'],
    salaryRange: [2500, 3000],
    requiredSkills: ['Qualificação', 'CRM Pipedrive', 'Comunicação Escrita'],
    cultureFit: ['Organização', 'Curiosidade', 'Empatia'],
    active: true,
    postedAt: '2023-10-28',
    companyDescription: 'Startup focada em educação corporativa, trazendo cursos rápidos e práticos para o mercado.',
    productSolution: 'Plataforma de Treinamento de Vendas Gamificada. Resolve o problema de engajamento em treinamentos tradicionais.',
    website: 'https://startvendas.edu',
    instagram: 'https://instagram.com/startvendas',
    compensationDetails: 'Fixo R$ 2.500 + R$ 10,00 por SAL (Sales Accepted Lead). Teto de comissão R$ 2.000.',
    deadline: '2023-11-10',
    icp: 'Pequenos empresários, Líderes de Vendas e profissionais liberais que buscam capacitação rápida.',
    idealProfile: 'Jovem, comunicativo e ágil. Alguém que goste de conversar e tenha raciocínio rápido para qualificar leads quentes.',
    techStack: ['Pipedrive', 'WhatsApp Business API', 'Aircall', 'Typeform'],
    dailyRoutine: ['08:00 - Limpeza de Inbox', '09:00 - Qualificação de Leads (Speed to Lead)', '12:00 - Almoço', '14:00 - Follow-up de No-Shows', '16:00 - Reunião com Marketing'],
    tacticalMandate: "Para esta missão na StartVendas, o cenário é claro: precisamos de alguém capaz de evangelizar e vender Plataforma de Treinamento de Vendas Gamificada diretamente para Pequenos empresários, Líderes de Vendas e profissionais liberais que buscam capacitação rápida, navegando por tomadores de decisão exigentes. O perfil tático é de um 'Hunter' obstinado: alguém que suporte a rejeição, cumpra a cadência de prospecção sem falhas e alimente o pipeline. O principal obstáculo será reduzir lead time para < 5 min, exigindo resiliência diária. A recompensa está na mesa: pacote de até R$ 3k com Fixo R$ 2.500 + R$ 10,00 por SAL (Sales Accepted Lead). Teto de comissão R$ 2.000."
  },
  // ... other jobs (fallback provided in code logic)
];
